version: "3.7"
services:
    controller:
      build:
        context: controller
      container_name: controller
      hostname: controller
      networks:
        - edgvision
      environment:
        - MANIPULATOR_HOST=manipulator
        - MANIPULATOR_PORT=9998

    sensor:
      build:
        context: sensor
      hostname: sensor
      networks:
        - edgvision
      environment:
        - CONTROLLER_HOST=controller
        - CONTROLLER_PORT=9999
      restart: always

    manipulator:
        build:
          context: manipulator
        container_name: manipulator
        hostname: manipulator
        networks:
          - edgvision
        environment:
          - MANIPULATOR_HOST=manipulator
          - MANIPULATOR_PORT=9998
networks:
  edgvision:
    name: edgvision
    driver: bridge
